version: "3"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/vue_app
    environment:
      - NODE_ENV=development
    command: sh -c "npm run serve"
